### PR TITLE
Move to Expand-Archive

### PR DESCRIPTION
**Pull request by mark-hallman**
Replaced the 7zip dependency by moving to Expand-Archive.  EZ is doing this too in his update scripts.

### CODE REVIEW

**Comment by grayfold3d** [comment]
Interesting. Just seeing his change now. I guess that changes the script requirements to PowerShell 5 or greater.  I certainly like that as an option but think I would update the code to check for the existence of the archive cmdlets first. See below. That gives it more flexibility for users that may not be on PS 5+.

Thoughts?

`if(!(Get-Command Expand-Archive -ErrorAction SilentlyContinue)){
    'Do 7zip stuff'
} 
else 
{
    Expand-Archive -Path $destFile -DestinationPath "." -Force
}`

**Comment by mark-hallman** [comment]
Mike,

Great point about the backward compatibility.  I think your approach is preferred.

-Mark

**Comment by mark-hallman** [comment]
Mike,

Could you shoot me an email at mark.hallman@gmail.com.  I would like to talk about some additional enhancements to your script.  

-Mark

**Comment by grayfold3d** [comment]
Closing this out as discussed. 7Zip dependency removed and additional functionality implemented. Thanks for the feedback and suggestions!

**Pull request closed without merging**
